
use Whearehouse
go
select TABLE_NAME from INFORMATION_SCHEMA.TABLES


INSERT INTO Regions VALUES ('Россия', 'Московская', 'Королев', 'ул.Мира, 15','387-23-04', '387-23-05')
INSERT INTO Regions (Area, City, Adress, Fax)  VALUES ('', 'Минск', 'ул.Гикало, 9', '278-83-88')	
INSERT INTO Regions (Area, City, Adress, Fax) VALUES ('Минская', 'Воложин', 'ул.Серова, 11', '48-37-92')
INSERT INTO Regions (Area, City, Adress, Phone, Fax) VALUES ('', 'Минск', 'ул.Кирова, 24', '269-13-76','269-13-77')	
INSERT INTO Regions (Area, City, Adress, Fax) VALUES ('Витебская', 'Полоцк', 'ул.Лесная, 6', '48-24-12')
INSERT INTO Regions VALUES ('Украина', 'Крымская', 'Алушта', 'ул.Франко, 24', NULL, '46-49-16')	
 GO

INSERT INTO Currencies(Name_Currency, Exchange_Rate) VALUES ( 'BYR', '1')	
INSERT INTO Currencies (Name_Currency, Exchange_Rate) VALUES ('USD','2.45')
INSERT INTO Currencies (Name_Currency, Step_Round, Exchange_Rate) VALUES ('EUR', '0.45','2.30')
 GO

--Insert Providers
INSERT INTO Providers([Name_Provider],[Payment_Term],[Key_Region],[Note]) VALUES('Ligula Elit Ltd','Безналичный расчет',1,'Lorem'),('Justo Incorporated','Предоплата',6,'Lorem'),('Fusce Industries','Безналичный расчет',4,'Lorem'),('Aptent Institute','Безналичный расчет',5,'Lorem'),('Non Institute','Предоплата',1,'Lorem'),('Dolor Fusce Inc.','Предоплата',5,'Lorem'),('Aliquam Rutrum LLP','Безналичный расчет',2,'Lorem'),('Luctus LLP','Безналичный расчет',4,'Lorem'),('Amet Ornare Lectus Limited','Безналичный расчет',5,'Lorem'),('Fringilla Purus Mauris PC','Предоплата',2,'Lorem');
INSERT INTO Providers([Name_Provider],[Payment_Term],[Key_Region],[Note]) VALUES('Feugiat Placerat Velit Incorporated','Безналичный расчет',3,'Lorem'),('Mauris Magna Duis Institute','Предоплата',3,'Lorem'),('Sed Neque Sed Incorporated','Предоплата',5,'Lorem'),('Phasellus Vitae Mauris Corporation','Предоплата',4,'Lorem'),('Egestas Aliquam Incorporated','Безналичный расчет',6,'Lorem'),('Pede Nunc Sed Foundation','Предоплата',2,'Lorem'),('Erat LLP','Безналичный расчет',1,'Lorem'),('Varius Corp.','Предоплата',3,'Lorem'),('Rhoncus Company','Безналичный расчет',3,'Lorem'),('Orci Phasellus Company','Предоплата',3,'Lorem');
INSERT INTO Providers([Name_Provider],[Payment_Term],[Key_Region],[Note]) VALUES('Sit Amet Consectetuer Inc.','Безналичный расчет',3,'Lorem'),('Ridiculus Mus LLC','Предоплата',1,'Lorem'),('Eu Lacus Industries','Безналичный расчет',1,'Lorem'),('Vulputate Ullamcorper Magna PC','Безналичный расчет',3,'Lorem'),('Auctor Vitae Industries','Предоплата',6,'Lorem'),('Nunc Sollicitudin Commodo LLC','Безналичный расчет',6,'Lorem'),('Magnis Dis Parturient LLP','Предоплата',1,'Lorem'),('Sodales Elit LLP','Предоплата',3,'Lorem'),('Vel Est LLP','Безналичный расчет',2,'Lorem'),('Neque Vitae Semper PC','Предоплата',5,'Lorem');
INSERT INTO Providers([Name_Provider],[Payment_Term],[Key_Region],[Note]) VALUES('Id Incorporated','Предоплата',6,'Lorem'),('Proin Velit Limited','Предоплата',1,'Lorem'),('Elit PC','Предоплата',3,'Lorem'),('Faucibus Leo PC','Предоплата',1,'Lorem'),('Quis Turpis Corporation','Предоплата',2,'Lorem'),('Cras Vulputate Velit Incorporated','Безналичный расчет',5,'Lorem'),('Egestas Rhoncus Proin Associates','Безналичный расчет',3,'Lorem'),('A Facilisis Non Ltd','Предоплата',5,'Lorem'),('Ut Tincidunt Orci Company','Безналичный расчет',4,'Lorem'),('Facilisis Lorem Tristique Inc.','Предоплата',4,'Lorem');
INSERT INTO Providers([Name_Provider],[Payment_Term],[Key_Region],[Note]) VALUES('Pede Et Corp.','Безналичный расчет',5,'Lorem'),('Consectetuer Adipiscing Institute','Предоплата',1,'Lorem'),('Leo In Lobortis LLC','Безналичный расчет',2,'Lorem'),('Feugiat Lorem Incorporated','Безналичный расчет',3,'Lorem'),('At Libero Inc.','Безналичный расчет',2,'Lorem'),('Felis Company','Предоплата',1,'Lorem'),('Nam PC','Предоплата',2,'Lorem'),('Adipiscing Elit Etiam Ltd','Предоплата',6,'Lorem'),('A Auctor Inc.','Безналичный расчет',4,'Lorem'),('Aliquet Metus Urna LLC','Предоплата',2,'Lorem');
INSERT INTO Providers([Name_Provider],[Payment_Term],[Key_Region],[Note]) VALUES('Accumsan Neque Et Foundation','Предоплата',3,'Lorem'),('Fermentum Vel Mauris Industries','Предоплата',2,'Lorem'),('Pharetra Institute','Безналичный расчет',2,'Lorem'),('Feugiat Non Lobortis LLP','Предоплата',6,'Lorem'),('Nisi Corp.','Безналичный расчет',6,'Lorem'),('Tellus Corporation','Безналичный расчет',5,'Lorem'),('Sed Eu Foundation','Безналичный расчет',5,'Lorem'),('Lorem Tristique Associates','Безналичный расчет',4,'Lorem'),('Odio Tristique Pharetra Industries','Предоплата',5,'Lorem'),('Pharetra Ut Ltd','Предоплата',4,'Lorem');
INSERT INTO Providers([Name_Provider],[Payment_Term],[Key_Region],[Note]) VALUES('Sagittis Ltd','Предоплата',2,'Lorem'),('Ligula Corp.','Безналичный расчет',2,'Lorem'),('Eros Proin Ultrices Associates','Безналичный расчет',5,'Lorem'),('Mollis Dui In LLP','Предоплата',6,'Lorem'),('Felis Nulla Associates','Безналичный расчет',4,'Lorem'),('Arcu Imperdiet Ltd','Предоплата',5,'Lorem'),('Velit Eu Sem LLP','Безналичный расчет',2,'Lorem'),('Morbi Neque Consulting','Предоплата',6,'Lorem'),('Amet Incorporated','Предоплата',4,'Lorem'),('Risus Limited','Предоплата',3,'Lorem');
INSERT INTO Providers([Name_Provider],[Payment_Term],[Key_Region],[Note]) VALUES('Vel Nisl Quisque Industries','Безналичный расчет',5,'Lorem'),('Non Hendrerit Id Limited','Безналичный расчет',4,'Lorem'),('Neque PC','Безналичный расчет',2,'Lorem'),('Elementum Sem Vitae LLC','Предоплата',4,'Lorem'),('Auctor Vitae Foundation','Безналичный расчет',1,'Lorem'),('Montes Nascetur Ridiculus Company','Предоплата',2,'Lorem'),('Nam Nulla Industries','Предоплата',1,'Lorem'),('Cursus Institute','Предоплата',6,'Lorem'),('Dui Institute','Предоплата',6,'Lorem'),('Non Associates','Предоплата',1,'Lorem');
INSERT INTO Providers([Name_Provider],[Payment_Term],[Key_Region],[Note]) VALUES('Integer Vitae LLC','Предоплата',3,'Lorem'),('Orci Luctus Et Incorporated','Безналичный расчет',4,'Lorem'),('Felis Nulla Industries','Предоплата',4,'Lorem'),('Metus Urna Industries','Безналичный расчет',5,'Lorem'),('Blandit Nam Institute','Предоплата',4,'Lorem'),('Et LLC','Предоплата',5,'Lorem'),('Etiam Gravida Molestie LLC','Безналичный расчет',5,'Lorem'),('Donec Felis Foundation','Безналичный расчет',3,'Lorem'),('Elit Curabitur Sed Corp.','Безналичный расчет',2,'Lorem'),('In Molestie Tortor Associates','Предоплата',5,'Lorem');
INSERT INTO Providers([Name_Provider],[Payment_Term],[Key_Region],[Note]) VALUES('Cursus Et Magna PC','Предоплата',4,'Lorem'),('Urna Ut Tincidunt Corporation','Предоплата',2,'Lorem'),('Fermentum Arcu Vestibulum LLP','Безналичный расчет',6,'Lorem'),('Ullamcorper Eu Limited','Предоплата',4,'Lorem'),('Morbi Tristique Associates','Предоплата',6,'Lorem'),('Duis Incorporated','Предоплата',1,'Lorem'),('Arcu Foundation','Предоплата',4,'Lorem'),('Accumsan Laoreet Foundation','Предоплата',4,'Lorem'),('Condimentum Eget Company','Безналичный расчет',6,'Lorem'),('Leo Elementum Sem Corp.','Безналичный расчет',3,'Lorem');
go
--Insert Clients

INSERT INTO Clients([Name_Client],[Name_Director],[Surname_Director],[Patronymic_Director],[Key_Region]) VALUES('Vitae Foundation','Eric','Brennan','Kadeem',2),('Dolor Donec Fringilla Ltd','Lucas','Neal','Idola',1),('Facilisis Facilisis Magna Company','Igor','Mcconnell','Fritz',5),('Duis Risus Associates','Sylvester','Leonard','Burton',6),('Augue Corp.','Chandler','Fields','Maia',5),('Ac Risus Corp.','Cain','Arnold','Samson',6),('Nec LLC','Basil','Welch','Daniel',4),('Vitae Odio Institute','Lucas','Hess','Cadman',6),('Turpis Inc.','Berk','Bentley','Zeus',5),('Suspendisse Commodo Tincidunt Inc.','Hayes','Padilla','Cameron',1);
INSERT INTO Clients([Name_Client],[Name_Director],[Surname_Director],[Patronymic_Director],[Key_Region]) VALUES('Vestibulum Accumsan Neque Associates','Jared','Mcintyre','Russell',3),('Integer Mollis Institute','Xenos','Mcconnell','Jemima',5),('Suspendisse Sagittis Industries','Brent','Bright','Jolene',6),('Penatibus Et Ltd','Aquila','Hurst','Amaya',4),('Eleifend Non Dapibus Incorporated','Basil','Warren','Danielle',2),('Neque Associates','Abel','Bradford','Jana',6),('Ante Ipsum Primis Corporation','Lane','Cunningham','Cassidy',5),('Nunc Institute','Shad','Mcdaniel','Sarah',4),('Sodales Purus In Company','Chaney','Green','Kylee',5),('Nunc Limited','Ethan','Navarro','Katell',1);
INSERT INTO Clients([Name_Client],[Name_Director],[Surname_Director],[Patronymic_Director],[Key_Region]) VALUES('Nisl Sem Consequat Ltd','Timothy','Gonzalez','Oliver',4),('Sapien Consulting','Armando','Rios','Nerea',6),('Nunc Mauris Ltd','Bruce','Kirkland','Venus',4),('Erat Volutpat LLC','Lamar','Lee','Hilda',1),('Aliquam Rutrum Corporation','Levi','Snyder','Sasha',3),('Consequat Institute','Odysseus','Head','Elijah',6),('Tristique Senectus Et Ltd','Hamish','Chase','Nomlanga',6),('Purus Mauris Foundation','Kenneth','Larson','Gay',5),('Ut Odio Industries','Xander','Leon','Eagan',6),('Ut Eros Non Industries','Quinn','Kramer','Elijah',6);
INSERT INTO Clients([Name_Client],[Name_Director],[Surname_Director],[Patronymic_Director],[Key_Region]) VALUES('Aenean Limited','Charles','Francis','Colt',2),('Ipsum Curabitur Consequat Incorporated','Dylan','Golden','Jamalia',2),('Dictum Foundation','Nissim','Glenn','Cade',3),('Dapibus PC','Curran','Townsend','Fuller',5),('Lectus Institute','Arden','Mcconnell','Philip',5),('Metus Vitae Industries','Kennan','Carr','Cailin',3),('Ultrices Mauris Ipsum Consulting','Dante','Potter','Colt',6),('Mattis Inc.','Wylie','Welch','Bryar',6),('Lorem Ltd','Jack','Finch','Matthew',3),('Vehicula Et Rutrum Foundation','Asher','Rosa','Dale',2);
INSERT INTO Clients([Name_Client],[Name_Director],[Surname_Director],[Patronymic_Director],[Key_Region]) VALUES('Eget Metus Eu LLC','Mannix','Joyner','Samuel',2),('Nonummy LLC','Mufutau','Cunningham','Whoopi',4),('Aliquet Magna A Company','Fuller','Beasley','Lavinia',5),('Phasellus Company','Dexter','Mayer','Elvis',2),('Scelerisque PC','Thaddeus','Stone','Kyle',6),('Adipiscing Elit Etiam Associates','Geoffrey','Jimenez','Basil',2),('Et Libero LLC','Anthony','Vincent','Alexa',4),('In Molestie Corporation','Gil','Maddox','Mallory',6),('Adipiscing Lacus Ut Corporation','Wyatt','Mercer','Axel',2),('Curabitur Egestas Nunc Institute','Raphael','Cameron','Caldwell',5);
INSERT INTO Clients([Name_Client],[Name_Director],[Surname_Director],[Patronymic_Director],[Key_Region]) VALUES('Nec Tempus Mauris LLC','Jeremy','Cooke','Kadeem',5),('Dapibus Consulting','Colby','Maddox','Carl',6),('Tincidunt Dui Limited','Prescott','Campbell','Norman',6),('Sed Dictum Eleifend Incorporated','Connor','Bush','Paul',4),('Ipsum Ac Mi Ltd','Akeem','Roberson','Gavin',4),('Lectus Pede Ltd','Arthur','Snow','Jillian',4),('Non Associates','Edan','Schwartz','Colt',2),('Posuere Cubilia Corporation','Dale','Atkins','Elmo',5),('Aliquet Diam Corp.','Alan','Alexander','Tarik',5),('Commodo Corp.','Upton','Harmon','Carl',2);
INSERT INTO Clients([Name_Client],[Name_Director],[Surname_Director],[Patronymic_Director],[Key_Region]) VALUES('A Foundation','Finn','Lott','Malachi',4),('Faucibus Orci Luctus Inc.','Uriel','Gamble','Troy',3),('Fusce Aliquet Ltd','Darius','Garner','Phillip',3),('At LLC','Dolan','Kramer','Akeem',1),('Metus In Ltd','Arden','Peck','Keefe',2),('Faucibus Lectus A Associates','Ian','Murphy','Velma',4),('Magna LLP','Basil','Elliott','Sydnee',5),('Luctus Et Ltd','Lionel','King','Hasad',3),('Cras Dolor Dolor Ltd','Beau','Spears','Boris',2),('Neque Incorporated','Caldwell','Horn','Cole',5);
INSERT INTO Clients([Name_Client],[Name_Director],[Surname_Director],[Patronymic_Director],[Key_Region]) VALUES('Eleifend Egestas LLC','Baker','Ward','Curran',2),('Diam Vel Institute','Carlos','Rivers','Zelenia',2),('Malesuada Fames Inc.','Logan','Britt','Cheyenne',1),('Non Ante Bibendum Industries','Hammett','Wyatt','Oleg',4),('Magna PC','Thomas','Terrell','Calvin',2),('Nulla Eu Corp.','Lev','Howe','Lewis',4),('Egestas LLC','Reed','Salinas','Melanie',1),('Vel Vulputate Eu Ltd','Coby','Romero','Bruno',2),('Euismod Urna Industries','Blaze','Welch','Graiden',1),('Blandit Corporation','Deacon','Stone','Aphrodite',1);
INSERT INTO Clients([Name_Client],[Name_Director],[Surname_Director],[Patronymic_Director],[Key_Region]) VALUES('Nulla Incorporated','Daquan','Parrish','Lynn',1),('Nulla Vulputate Consulting','Fritz','Payne','Colt',2),('Lacinia At Iaculis Institute','Jerry','Giles','Briar',2),('Aenean Sed Incorporated','Josiah','Pollard','Tad',4),('In Consulting','Eaton','Garrison','Clarke',4),('Erat Eget Ipsum Incorporated','Thor','Barlow','Barclay',1),('A Scelerisque Company','Herrod','Bentley','Brent',5),('Neque Tellus Incorporated','Bernard','Frazier','Sloane',2),('Habitant Industries','Jameson','Davenport','Zephania',6),('Tristique Neque Institute','Michael','Mooney','Hiram',5);
INSERT INTO Clients([Name_Client],[Name_Director],[Surname_Director],[Patronymic_Director],[Key_Region]) VALUES('Euismod Enim Company','Fletcher','West','Ima',1),('Orci Ut Semper LLP','Ray','Gross','Jerome',2),('Metus Sit Inc.','Macaulay','Williams','Uriah',4),('Luctus Ipsum Foundation','Seth','Cote','Beverly',2),('Fringilla Purus Mauris Inc.','Thaddeus','Hill','Gray',4),('Euismod Limited','Samuel','Mejia','Denton',3),('Consequat Corp.','Rudyard','Hess','Geraldine',1),('Montes Foundation','Justin','Thornton','Acton',1),('At Institute','Josiah','Burgess','Guy',3),('Integer Id Institute','Louis','Steele','Abel',6);
go
--Insert Products
INSERT INTO Products([Name_Product],[Price],[Key_Currency],[Packaged]) VALUES('Odio PC','13360',3,'да'),('Proin Vel Consulting','65537',3,'да'),('Sagittis Augue Eu Foundation','62864',1,'да'),('Enim LLP','6692',2,'нет'),('Curabitur Consequat Inc.','83914',2,'нет'),('Imperdiet LLC','35136',1,'да'),('Amet Faucibus Company','53329',3,'нет'),('Semper Dui Industries','62461',3,'да'),('Rhoncus Donec Est Limited','58400',2,'нет'),('Egestas Corporation','59179',2,'нет');
INSERT INTO Products([Name_Product],[Price],[Key_Currency],[Packaged]) VALUES('Est Inc.','90326',1,'нет'),('Egestas Hendrerit Neque Corporation','69156',2,'нет'),('Ornare Lectus Justo Corp.','94248',2,'да'),('Lacus Cras Interdum Corp.','14099',1,'нет'),('Eget Dictum Placerat Inc.','21861',2,'нет'),('Aliquet Sem Company','55296',1,'да'),('Suspendisse Aliquet Sem Ltd','88183',3,'нет'),('At Auctor Corp.','55495',2,'да'),('Ultrices A Auctor Industries','3180',3,'нет'),('Tellus Sem Mollis Associates','19806',2,'да');
INSERT INTO Products([Name_Product],[Price],[Key_Currency],[Packaged]) VALUES('Litora Torquent Company','22472',2,'да'),('Nibh Quisque Nonummy Company','18377',1,'нет'),('Amet Faucibus Ut PC','54367',2,'нет'),('Elit LLP','29949',1,'да'),('Nec Tempus Scelerisque LLP','82433',2,'нет'),('Nullam Enim Sed Corp.','19045',3,'да'),('Velit Industries','40725',1,'нет'),('Sed Malesuada LLP','75455',1,'да'),('Dui In Institute','29314',3,'да'),('Magna Duis Limited','30004',1,'нет');
INSERT INTO Products([Name_Product],[Price],[Key_Currency],[Packaged]) VALUES('Nascetur Limited','10257',2,'нет'),('Varius Orci In Corporation','67829',3,'да'),('Facilisis Magna Tellus Ltd','53305',2,'нет'),('Nisi Dictum Augue LLC','15620',1,'нет'),('Vulputate Velit Inc.','90830',3,'да'),('At Foundation','47696',1,'нет'),('Hendrerit Inc.','12068',2,'да'),('Id LLP','93693',1,'да'),('Mauris Vestibulum Neque Corporation','31855',2,'нет'),('Luctus Vulputate Ltd','99885',3,'нет');
INSERT INTO Products([Name_Product],[Price],[Key_Currency],[Packaged]) VALUES('Malesuada Malesuada Integer Associates','12816',3,'нет'),('Aliquam Eros Turpis Corporation','87565',2,'да'),('Aenean Massa PC','68406',1,'да'),('Lorem Semper Industries','54742',2,'да'),('Diam Duis Mi Incorporated','59305',1,'да'),('Sed Molestie Sed Corporation','44838',1,'да'),('Velit Cras Incorporated','9106',1,'нет'),('Nascetur LLP','96234',2,'нет'),('Quis Turpis Vitae LLP','87990',2,'да'),('Et Magnis Dis Institute','13221',1,'да');
INSERT INTO Products([Name_Product],[Price],[Key_Currency],[Packaged]) VALUES('Tincidunt Nibh Associates','56280',1,'нет'),('At Associates','17909',3,'да'),('Quisque Imperdiet Corp.','63326',2,'нет'),('Tellus Suspendisse LLP','67436',2,'да'),('Elit A Feugiat Foundation','63662',3,'нет'),('Id Magna Inc.','75764',1,'нет'),('Ridiculus Mus Proin Associates','20473',2,'нет'),('Porta LLC','89879',2,'нет'),('Vitae Diam Proin Industries','58773',2,'да'),('Justo Corporation','84640',2,'нет');
INSERT INTO Products([Name_Product],[Price],[Key_Currency],[Packaged]) VALUES('Senectus Corp.','98281',2,'да'),('Ornare Egestas Ligula Consulting','82229',3,'нет'),('Eget Metus Eu Incorporated','61050',1,'нет'),('Et Magnis Dis Ltd','88365',2,'нет'),('Nascetur Ridiculus Mus Limited','93971',1,'нет'),('Nisi Mauris Nulla Consulting','92631',2,'да'),('Nibh Corp.','90370',2,'да'),('Vitae Consulting','91614',2,'нет'),('Nulla Facilisi Sed Associates','94215',1,'да'),('Magna Foundation','23656',3,'да');
INSERT INTO Products([Name_Product],[Price],[Key_Currency],[Packaged]) VALUES('Auctor Mauris Company','26836',3,'нет'),('Gravida Sagittis Corporation','5951',1,'нет'),('Phasellus Dolor Associates','80045',2,'нет'),('Nec LLC','48278',1,'нет'),('Rhoncus Proin Associates','70336',3,'да'),('Ut Semper Institute','69435',1,'нет'),('Lorem Eget Corp.','89559',3,'нет'),('Non Industries','41251',2,'нет'),('Nibh Enim Gravida Company','37156',1,'нет'),('Nulla LLC','24791',3,'нет');
INSERT INTO Products([Name_Product],[Price],[Key_Currency],[Packaged]) VALUES('Dolor Corp.','15553',3,'нет'),('Vel Sapien Corporation','19404',2,'нет'),('Egestas Lacinia Sed Corporation','47379',3,'да'),('Pharetra Nibh Aliquam Corp.','93174',2,'нет'),('Interdum Nunc Sollicitudin Ltd','0655',3,'да'),('Placerat Industries','50723',2,'да'),('Tristique Ac Limited','5187',1,'нет'),('Volutpat Nulla Dignissim Foundation','27211',1,'нет'),('Sed Id LLC','51974',2,'нет'),('Mauris Erat Eget Consulting','16249',2,'нет');
INSERT INTO Products([Name_Product],[Price],[Key_Currency],[Packaged]) VALUES('Ullamcorper Eu LLC','9793',1,'да'),('Quam A LLC','90152',2,'нет'),('Facilisi Foundation','97354',1,'нет'),('Iaculis Lacus Pede LLP','70604',1,'да'),('Lobortis Augue Scelerisque Company','2170',3,'нет'),('Hendrerit Neque In Inc.','62094',3,'да'),('Convallis In Cursus Inc.','40614',3,'да'),('Faucibus LLP','56522',3,'да'),('Aliquet LLP','68189',2,'да'),('Lectus Quis Massa Incorporated','94257',3,'нет');
go

--Insert Orders
INSERT INTO Orders([Key_Client],[Key_Product],[Count_Order_Product],[Key_Provider]) VALUES(5,63,27,6),(4,86,67,24),(75,30,74,82),(34,45,29,59),(41,43,21,50),(94,34,194,23),(53,12,63,75),(48,89,111,99),(2,38,141,28),(78,33,142,89);
INSERT INTO Orders([Key_Client],[Key_Product],[Count_Order_Product],[Key_Provider]) VALUES(92,37,173,1),(31,32,27,42),(41,47,36,65),(28,49,169,48),(75,49,46,72),(14,77,61,40),(22,96,51,73),(95,85,120,21),(7,87,32,81),(74,13,152,41);
INSERT INTO Orders([Key_Client],[Key_Product],[Count_Order_Product],[Key_Provider]) VALUES(55,15,49,47),(48,54,20,80),(34,31,184,11),(66,75,75,46),(31,79,53,31),(57,91,66,92),(53,71,73,32),(61,58,186,30),(60,69,95,90),(19,77,58,90);
INSERT INTO Orders([Key_Client],[Key_Product],[Count_Order_Product],[Key_Provider]) VALUES(37,81,113,31),(60,36,75,59),(67,82,170,84),(13,99,105,60),(67,78,127,58),(72,63,75,20),(14,97,186,37),(4,17,35,51),(48,28,27,82),(23,81,43,43);
INSERT INTO Orders([Key_Client],[Key_Product],[Count_Order_Product],[Key_Provider]) VALUES(29,40,129,97),(63,65,150,87),(39,26,194,94),(39,8,97,1),(59,89,57,79),(23,99,34,4),(60,70,191,79),(70,38,199,44),(8,97,20,87),(71,15,89,47);
INSERT INTO Orders([Key_Client],[Key_Product],[Count_Order_Product],[Key_Provider]) VALUES(25,73,124,98),(80,71,110,97),(45,82,189,32),(15,66,2,47),(97,49,144,56),(79,59,44,81),(95,51,73,49),(40,10,176,4),(7,3,29,60),(27,92,10,56);
INSERT INTO Orders([Key_Client],[Key_Product],[Count_Order_Product],[Key_Provider]) VALUES(90,36,129,58),(21,26,1,56),(58,49,145,18),(87,31,16,91),(9,37,60,45),(99,22,181,11),(95,98,109,41),(30,1,72,88),(41,65,17,7),(25,11,44,100);
INSERT INTO Orders([Key_Client],[Key_Product],[Count_Order_Product],[Key_Provider]) VALUES(15,31,68,51),(1,57,171,46),(83,93,173,29),(13,85,180,20),(87,39,128,48),(40,5,96,79),(30,58,97,48),(80,19,189,14),(49,43,89,7),(19,60,30,31);
INSERT INTO Orders([Key_Client],[Key_Product],[Count_Order_Product],[Key_Provider]) VALUES(86,73,142,19),(20,31,49,80),(51,83,185,55),(32,28,122,29),(40,45,140,3),(96,24,84,37),(90,41,6,63),(56,25,185,82),(12,25,199,59),(7,74,198,32);
INSERT INTO Orders([Key_Client],[Key_Product],[Count_Order_Product],[Key_Provider]) VALUES(1,10,167,41),(72,99,113,15),(56,4,169,71),(21,37,8,76),(15,7,157,100),(68,100,87,23),(13,91,172,93),(59,49,3,71),(23,67,191,40),(66,18,78,9);
go

INSERT INTO Orders([Key_Client],[Key_Product],[Count_Order_Product],[Key_Provider],Delivety_Time) VALUES(1,24,34,90,GETDATE()+46)

DELETE FROM Orders
go
DBCC CHECKIDENT (Orders, RESEED, 0)

 CREATE VIEW ProductOrderView AS
   SELECT Products.Name_Product, Orders.Count_Order_Product, 
     Products.Unit_Product, Providers.Name_Provider
   FROM Orders INNER JOIN Providers ON Orders.Key_Provider = Providers.Key_Provider 
			 INNER JOIN Products ON Orders.Key_Product = Products.Key_Product
 GO

 select * from Products
  select * from Providers
   select * from Regions
    select * from Currencies
	 select * from Clients
	  select * from  Orders

 select * from ProductOrderView

